language: java

os: linux
dist: trusty
sudo: false
addons:
  sauce_connect:
    username: "bazel_rules_webtesting"
    access_key: "c5bed09c-a8a6-44c8-af02-a545905f957f"
jdk: openjdk8

env:
  - V=0.11.0

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      OS=linux
    fi

    BAZEL_INSTALLER="bazel-${V}-without-jdk-installer-${OS}-x86_64.sh"

    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/${BAZEL_INSTALLER}"
    wget "${URL}"
    chmod +x "./${BAZEL_INSTALLER}"
    "./${BAZEL_INSTALLER}" --user

    bazel fetch --config=ci //...

script:
  - bazel test --config=ci //...

notifications:
  email: false
