os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - wget
            - pkg-config
            - zip
            - g++
            - zlib1g-dev
            - unzip
            - python
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.2

env:
  - V=0.11.0

cache:
  directories:
  - $HOME/.cache
  - $HOME/bin

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      OS=linux
    fi

    BAZEL_INSTALLER="bazel-${V}-without-jdk-installer-${OS}-x86_64.sh"
    BAZEL_INSTALLER_PATH="${HOME}/.cache/installers/${BAZEL_INSTALLER}"

    if [[ ! -f "${BAZEL_INSTALLER_PATH}" ]]; then
      rm -rf "${HOME}/.cache/installers"
      rm -rf "${HOME}/bin/*"
      mkdir -p "${HOME}/.cache/installers"
      URL="https://github.com/bazelbuild/bazel/releases/download/${V}/${BAZEL_INSTALLER}"
      wget -O "${BAZEL_INSTALLER_PATH}" "${URL}"
      chmod +x "${BAZEL_INSTALLER_PATH}"
      "${BAZEL_INSTALLER_PATH}" --user
    fi

script:
  - bazel --output_base=$HOME/.cache/bazel test --config=ci //...

notifications:
  email: false
