dist: trusty
sudo: required
language: java

os: linux

env: V=0.26.0

addons:
  sauce_connect: true

before_install:
  - |
    OS=linux
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
    - |
      bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      test \
      --test_tag_filters=-notravis,-noci \
      --test_output=streamed \
      --test_env=TUNNEL_IDENTIFIER="${TRAVIS_JOB_NUMBER}" \
      --test_env=BUILD_TAG="${TRAVIS_COMMIT}" \
      //...
